products:
  - pattern: "ridge/RadarImg/N0R/BGM/BGM_[0-9]{8}_[0-9]{4}_N0R.gif"
    date_fn: radar_file_date
    overlays:
      - Overlays/County/Short/BGM_County_Short.gif
      - Overlays/Highways/Short/BGM_Highways_Short.gif
      - Overlays/Rivers/Short/BGM_Rivers_Short.gif
      - Overlays/Cities/Short/BGM_City_Short.gif
    video: N0RBGM.mp4
    still: N0RBGM.png
  - pattern: ridge/RadarImg/N1P/BGM/BGM_[0-9]{8}_[0-9]{4}_N1P.gif
    date_fn: radar_file_date
    video: N1PBGM.mp4
    overlays:
      - Overlays/County/Short/BGM_County_Short.gif
      - Overlays/Highways/Short/BGM_Highways_Short.gif
      - Overlays/Rivers/Short/BGM_Rivers_Short.gif
      - Overlays/Cities/Short/BGM_City_Short.gif
    still: N1PBGM.png
  - pattern: Conus/RadarImg/northeast_[0-9]{8}_[0-9]{4}.gif
    date_fn: radar_file_date,
    video: northeast.mp4
